name: Automatisation des tests DevSecOps
on: push
jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Dependances
        run: |
          docker run --rm \
            -v "$PWD":/project \
            aquasec/trivy:latest fs \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            --file-patterns "pip:.*\.txt" \
            /project
  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Test Dockerfile
       run: |
          docker run --rm -i hadolint/hadolint hadolint --failure-threshold error - < Dockerfile
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
